version: '2'

services:
  api:
    image: "msosa/helloworld-api"
    networks:
    -  serko
  endpoint:
    image: "nginx:1.14.0"
    stdin_open: true
    tty: true
    command: ["nginx", "-g", "daemon off;"]
    ports:
    - "80:80"
    volumes:
    - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    networks:
    -  serko
networks:
  serko:
